### ISSUE TITLE
exception: TypeError: fullscreen error

### ISSUE THREAD

**Issue by codingyourlife** [liran/fullscreen-react#5]
sometimes on mobile page crashes with the message "fullscreen error". seems to come from screenfull which this package seems to build up onto.

this is from their readme:
```
if (screenfull.isEnabled) {
	screenfull.on('error', event => {
		console.error('Failed to enable fullscreen', event);
	});
}
```

I'm not sure if there is a workaround for this. Please fix.

**Comment by codingyourlife** [comment]
I have a proposal for a fix:
https://github.com/liran/fullscreen-react/pull/6

**Comment by liran** [comment]
thank your PR
